#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$$.tags"' EXIT

# place the tags file in the .git directory, now you don't have to add it to the .gitignore file.
git ls-files | ctags --tag-relative -L - -f "$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
