#!/bin/sh
set -e

current=`pwd`
backup="$HOME/.osx-settings-backup-`date +%s`"

# backup and create symlinks
for f in `ls $current/rc/`; do
  file=`basename $f`
  dest="$HOME/.$file"
  source="$current/rc/$file"

  if [[ -f $dest || -d $dest ]]; then
    mkdir -p $backup
    echo "Making backup of $dest in $backup"
    cp -R $dest $backup/$file
  fi

  echo "Symlinking: .$file"
  ln -fs $source $dest
done

# setup the git hooks for ctags
git_template="$HOME/.git_template"

git config --global init.templatedir $git_template
mkdir -p "$git_template/hooks"

for f in `ls $current/hooks/`; do
  file=`basename $f`
  dest="$git_template/hooks/$file"
  source="$current/hooks/$file"

  echo "Symlinking: $source to $dest"
  ln -fs $source $dest
done
