#!/bin/bash
exit_status=$1
result=""

function finish {
  exit_code_color
  prompt_type
  space
  append $reset
  echo $result
}

function exit_code_color {
  if [[ $exit_status == 0 ]]; then
    append $blue
  else
    append $red
  fi
}

function prompt_type {
  status=$(git status 2> /dev/null)
  if [[ $? == 0 ]]; then
    git_prompt
  else
    normal_prompt
  fi
}

function space {
  result="$result "
}

function append {
  result=$result$1
}

function basedir {
  if [ -n "$basedir" ]; then
    dir=$(cd $basedir; pwd)
  else
    dir=$PWD
  fi
  append $(basename $dir)
}

function config_mode {
  user_email=$(git config user.email)

  if [[ "$user_email" == "$HOME_AUTHOR_EMAIL" ]]; then
    current_mode='home'
  elif [[ "$user_email" == "$WORK_AUTHOR_EMAIL" ]]; then
    current_mode='work'
  else
    current_mode='unknown'
  fi

  space
  append $gray
  append $current_mode
}

function time_since_last_commit {
  minutes=$(minutes_since_last_commit)
  if [ "$minutes" -ne -1 ]; then
    space
    append $gray
    if [ "$minutes" -ge 518400 ]; then
      append $(($minutes/518400))
      append y
    elif [ "$minutes" -ge 43200 ]; then
      append $(($minutes/43200))
      append mo
    elif [ "$minutes" -ge 10080 ]; then
      append $(($minutes/10080))
      append w
    elif [ "$minutes" -ge 1440 ]; then
      append $(($minutes/1440))
      append d
    elif [ "$minutes" -ge 60 ]; then
      append $(($minutes/60))
      append h
    else
      append $minutes
      append m
    fi
  fi
}

function minutes_since_last_commit {
  now=`date +%s`
  last_commit=`git log --pretty=format:'%at' -1 2>/dev/null`
  if $lastcommit ; then
    seconds_since_last_commit=$((now-last_commit))
    minutes_since_last_commit=$((seconds_since_last_commit/60))
    echo $minutes_since_last_commit
  else
    echo "-1"
  fi
}

function branch {
  space
  if clean; then
    append $green
  else
    append $red
  fi
  append $branch
}

function branch_or_commit {
  branch=$(git branch | grep '^\*' | sed 's/^\*\ //')
  if [ "$branch" == "(no branch)" ]; then
    # when not on any branch, always color red
    echo "$red$(git rev-list -n 1 --abbrev-commit HEAD)"
  elif [ "$branch" == "" ]; then
    # you are not on any branch or commit
    echo "$red???"
  else
    echo $branch
  fi
}

function in_rebase {
  if [ -n "$basedir" ]; then
    dir=$basedir
  else
    dir='.'
  fi
  if [[ -d $dir/.git/rebase-apply ]]; then
    space
    append $yellow
    append "rebasing!"
  fi
}

function merge {
  append $magenta
  if ahead; then
    space
    append "↑"
  elif behind; then
    space
    append "↓"
  elif diverged; then
    space
    append "↕"
  fi
}

function subdir {
  space
  append $cyan
  append "/${subdir%/}"
}

function git_prompt {
  branch=$(branch_or_commit)
  subdir=$(git rev-parse --show-prefix)
  basedir=$(git rev-parse --show-cdup)
  basedir
  time_since_last_commit
  branch
  in_rebase
  merge
  config_mode
  subdir
}

function normal_prompt {
  append "${PWD/$HOME/~}"
}

function clean {
  echo $status | grep "nothing to commit, working tree clean" > /dev/null
}

function ahead {
  echo $status | grep 'Your branch is ahead' > /dev/null
}

function diverged {
  echo $status | grep 'have diverged' > /dev/null
}

function behind {
  echo $status | grep 'Your branch is behind' > /dev/null
}

finish
